import type { ChangeoverLog } from '../types/historical';

// 10 changeover observations: April 20–30, Lines 9 & 10
// Shows clear SMED progression in 3 phases:
//   Phase 1 (Apr 20–22): Baseline — no SMED, ad-hoc changeover
//   Phase 2 (Apr 23–26): Partial SMED — T-1 kitting + OB sheets introduced
//   Phase 3 (Apr 27–30): Full SMED — all T-1 tasks + parallel mechanics + setting cards

export const HISTORICAL_LOGS: ChangeoverLog[] = [
  // ── PHASE 1: BASELINE ──────────────────────────────────────────────────────
  {
    id: 'log-apr-20',
    date: '2026-04-20',
    lineId: 'line-9',
    fromStyleCode: 'ARL-SH-CARGO-24',
    toStyleCode: 'ARL-SH-CHINO-24',
    smedException: false,
    t1CompletionPct: 18,
    totalDurationMin: 104,
    internalTimeMin: 104,
    externalTimeSavedMin: 0,
    breakdown: { wipClearance: 24, machineSetup: 22, threadPrep: 15, attachmentHandling: 14, operatorDemo: 12, fabricStaging: 10, trialRun: 9, layoutAdjustment: 7 },
    rampUp: [
      { hour: 1, efficiency: 22, target: 45, piecesProduced: 18 },
      { hour: 2, efficiency: 30, target: 55, piecesProduced: 25 },
      { hour: 3, efficiency: 36, target: 65, piecesProduced: 30 },
      { hour: 4, efficiency: 40, target: 70, piecesProduced: 33 },
      { hour: 5, efficiency: 43, target: 75, piecesProduced: 36 },
      { hour: 6, efficiency: 45, target: 75, piecesProduced: 37 },
      { hour: 7, efficiency: 46, target: 75, piecesProduced: 38 },
      { hour: 8, efficiency: 47, target: 75, piecesProduced: 39 },
    ],
    defectRatePct: 18.4,
    notes: 'No T-1 prep. Attachments sourced during changeover. OB sheet not ready at start. Heavy WIP backlog on assembly.',
    phase: 'baseline',
  },
  {
    id: 'log-apr-21',
    date: '2026-04-21',
    lineId: 'line-10',
    fromStyleCode: 'ARL-SH-CHINO-24',
    toStyleCode: 'ARL-SH-DENIM-25',
    smedException: false,
    t1CompletionPct: 15,
    totalDurationMin: 110,
    internalTimeMin: 110,
    externalTimeSavedMin: 0,
    breakdown: { wipClearance: 26, machineSetup: 23, threadPrep: 16, attachmentHandling: 15, operatorDemo: 11, fabricStaging: 11, trialRun: 10, layoutAdjustment: 8 },
    rampUp: [
      { hour: 1, efficiency: 19, target: 45, piecesProduced: 16 },
      { hour: 2, efficiency: 27, target: 55, piecesProduced: 22 },
      { hour: 3, efficiency: 33, target: 65, piecesProduced: 27 },
      { hour: 4, efficiency: 38, target: 70, piecesProduced: 31 },
      { hour: 5, efficiency: 41, target: 75, piecesProduced: 34 },
      { hour: 6, efficiency: 43, target: 75, piecesProduced: 35 },
      { hour: 7, efficiency: 44, target: 75, piecesProduced: 36 },
      { hour: 8, efficiency: 45, target: 75, piecesProduced: 37 },
    ],
    defectRatePct: 21.2,
    notes: 'Denim style — new folder type caused 30 min additional machine setup. Mechanic had to fetch tools from workshop twice.',
    phase: 'baseline',
  },
  {
    id: 'log-apr-22',
    date: '2026-04-22',
    lineId: 'line-9',
    fromStyleCode: 'ARL-SH-DENIM-25',
    toStyleCode: 'ARL-SH-CARGO-24',
    smedException: false,
    t1CompletionPct: 22,
    totalDurationMin: 98,
    internalTimeMin: 98,
    externalTimeSavedMin: 0,
    breakdown: { wipClearance: 22, machineSetup: 20, threadPrep: 14, attachmentHandling: 13, operatorDemo: 11, fabricStaging: 9, trialRun: 8, layoutAdjustment: 6 },
    rampUp: [
      { hour: 1, efficiency: 25, target: 45, piecesProduced: 21 },
      { hour: 2, efficiency: 33, target: 55, piecesProduced: 27 },
      { hour: 3, efficiency: 39, target: 65, piecesProduced: 32 },
      { hour: 4, efficiency: 42, target: 70, piecesProduced: 35 },
      { hour: 5, efficiency: 45, target: 75, piecesProduced: 37 },
      { hour: 6, efficiency: 46, target: 75, piecesProduced: 38 },
      { hour: 7, efficiency: 47, target: 75, piecesProduced: 39 },
      { hour: 8, efficiency: 48, target: 75, piecesProduced: 40 },
    ],
    defectRatePct: 16.8,
    notes: 'Repeat style — slightly faster machine setup. Still no pre-prep.',
    phase: 'baseline',
  },

  // ── PHASE 2: PARTIAL SMED ──────────────────────────────────────────────────
  {
    id: 'log-apr-23',
    date: '2026-04-23',
    lineId: 'line-10',
    fromStyleCode: 'ARL-SH-CARGO-24',
    toStyleCode: 'ARL-SH-CHINO-24',
    smedException: true,
    t1CompletionPct: 48,
    totalDurationMin: 76,
    internalTimeMin: 62,
    externalTimeSavedMin: 28,
    breakdown: { wipClearance: 14, machineSetup: 18, threadPrep: 8, attachmentHandling: 7, operatorDemo: 5, fabricStaging: 8, trialRun: 8, layoutAdjustment: 6 },
    rampUp: [
      { hour: 1, efficiency: 34, target: 45, piecesProduced: 28 },
      { hour: 2, efficiency: 44, target: 55, piecesProduced: 36 },
      { hour: 3, efficiency: 51, target: 65, piecesProduced: 42 },
      { hour: 4, efficiency: 56, target: 70, piecesProduced: 46 },
      { hour: 5, efficiency: 59, target: 75, piecesProduced: 49 },
      { hour: 6, efficiency: 61, target: 75, piecesProduced: 50 },
      { hour: 7, efficiency: 62, target: 75, piecesProduced: 51 },
      { hour: 8, efficiency: 63, target: 75, piecesProduced: 52 },
    ],
    defectRatePct: 12.5,
    notes: 'First SMED pilot. Kitting done on T-1, OB sheets distributed. Threads pre-loaded. Mechanic still sequential.',
    phase: 'partial-smed',
  },
  {
    id: 'log-apr-24',
    date: '2026-04-24',
    lineId: 'line-9',
    fromStyleCode: 'ARL-SH-CHINO-24',
    toStyleCode: 'ARL-SH-DENIM-25',
    smedException: true,
    t1CompletionPct: 56,
    totalDurationMin: 68,
    internalTimeMin: 54,
    externalTimeSavedMin: 36,
    breakdown: { wipClearance: 10, machineSetup: 16, threadPrep: 6, attachmentHandling: 6, operatorDemo: 4, fabricStaging: 7, trialRun: 7, layoutAdjustment: 5 },
    rampUp: [
      { hour: 1, efficiency: 38, target: 45, piecesProduced: 31 },
      { hour: 2, efficiency: 49, target: 55, piecesProduced: 40 },
      { hour: 3, efficiency: 56, target: 65, piecesProduced: 46 },
      { hour: 4, efficiency: 61, target: 70, piecesProduced: 50 },
      { hour: 5, efficiency: 64, target: 75, piecesProduced: 53 },
      { hour: 6, efficiency: 66, target: 75, piecesProduced: 54 },
      { hour: 7, efficiency: 67, target: 75, piecesProduced: 55 },
      { hour: 8, efficiency: 68, target: 75, piecesProduced: 56 },
    ],
    defectRatePct: 10.2,
    notes: 'Layout sheet issued on T-1. WIP run-down schedule followed. Machine setting cards trialled for first time.',
    phase: 'partial-smed',
  },
  {
    id: 'log-apr-25',
    date: '2026-04-25',
    lineId: 'line-10',
    fromStyleCode: 'ARL-SH-DENIM-25',
    toStyleCode: 'ARL-SH-CARGO-24',
    smedException: true,
    t1CompletionPct: 62,
    totalDurationMin: 61,
    internalTimeMin: 48,
    externalTimeSavedMin: 43,
    breakdown: { wipClearance: 8, machineSetup: 14, threadPrep: 5, attachmentHandling: 5, operatorDemo: 4, fabricStaging: 6, trialRun: 6, layoutAdjustment: 4 },
    rampUp: [
      { hour: 1, efficiency: 42, target: 45, piecesProduced: 35 },
      { hour: 2, efficiency: 53, target: 55, piecesProduced: 44 },
      { hour: 3, efficiency: 60, target: 65, piecesProduced: 50 },
      { hour: 4, efficiency: 65, target: 70, piecesProduced: 53 },
      { hour: 5, efficiency: 68, target: 75, piecesProduced: 56 },
      { hour: 6, efficiency: 70, target: 75, piecesProduced: 57 },
      { hour: 7, efficiency: 71, target: 75, piecesProduced: 58 },
      { hour: 8, efficiency: 71, target: 75, piecesProduced: 58 },
    ],
    defectRatePct: 9.1,
    notes: 'Operator demo done on T-1 for changed operations. QC spec sheet issued. Significant improvement in trial run time.',
    phase: 'partial-smed',
  },
  {
    id: 'log-apr-26',
    date: '2026-04-26',
    lineId: 'line-9',
    fromStyleCode: 'ARL-SH-CARGO-24',
    toStyleCode: 'ARL-SH-CHINO-24',
    smedException: true,
    t1CompletionPct: 74,
    totalDurationMin: 44,
    internalTimeMin: 34,
    externalTimeSavedMin: 60,
    breakdown: { wipClearance: 5, machineSetup: 9, threadPrep: 4, attachmentHandling: 3, operatorDemo: 2, fabricStaging: 3, trialRun: 5, layoutAdjustment: 3 },
    rampUp: [
      { hour: 1, efficiency: 48, target: 50, piecesProduced: 40 },
      { hour: 2, efficiency: 58, target: 60, piecesProduced: 48 },
      { hour: 3, efficiency: 65, target: 68, piecesProduced: 53 },
      { hour: 4, efficiency: 70, target: 73, piecesProduced: 57 },
      { hour: 5, efficiency: 73, target: 75, piecesProduced: 60 },
      { hour: 6, efficiency: 75, target: 75, piecesProduced: 61 },
      { hour: 7, efficiency: 76, target: 75, piecesProduced: 62 },
      { hour: 8, efficiency: 76, target: 75, piecesProduced: 62 },
    ],
    defectRatePct: 7.4,
    notes: 'Two-mechanic parallel protocol trialled. Zone A and B worked simultaneously. Significant reduction in machine setup time.',
    phase: 'partial-smed',
  },

  // ── PHASE 3: FULL SMED ────────────────────────────────────────────────────
  {
    id: 'log-apr-27',
    date: '2026-04-27',
    lineId: 'line-10',
    fromStyleCode: 'ARL-SH-CHINO-24',
    toStyleCode: 'ARL-SH-DENIM-25',
    smedException: true,
    t1CompletionPct: 87,
    totalDurationMin: 36,
    internalTimeMin: 26,
    externalTimeSavedMin: 74,
    breakdown: { wipClearance: 4, machineSetup: 7, threadPrep: 2, attachmentHandling: 2, operatorDemo: 1, fabricStaging: 2, trialRun: 4, layoutAdjustment: 2 },
    rampUp: [
      { hour: 1, efficiency: 54, target: 55, piecesProduced: 44 },
      { hour: 2, efficiency: 64, target: 65, piecesProduced: 53 },
      { hour: 3, efficiency: 70, target: 70, piecesProduced: 57 },
      { hour: 4, efficiency: 74, target: 74, piecesProduced: 61 },
      { hour: 5, efficiency: 76, target: 75, piecesProduced: 62 },
      { hour: 6, efficiency: 77, target: 75, piecesProduced: 63 },
      { hour: 7, efficiency: 78, target: 75, piecesProduced: 64 },
      { hour: 8, efficiency: 78, target: 75, piecesProduced: 64 },
    ],
    defectRatePct: 5.8,
    notes: 'Full SOP followed. All 9 T-1 tasks completed before end of T-1 shift. Changeover trolley used for first time.',
    phase: 'full-smed',
  },
  {
    id: 'log-apr-28',
    date: '2026-04-28',
    lineId: 'line-9',
    fromStyleCode: 'ARL-SH-DENIM-25',
    toStyleCode: 'ARL-SH-CARGO-24',
    smedException: true,
    t1CompletionPct: 92,
    totalDurationMin: 30,
    internalTimeMin: 22,
    externalTimeSavedMin: 80,
    breakdown: { wipClearance: 3, machineSetup: 6, threadPrep: 2, attachmentHandling: 2, operatorDemo: 1, fabricStaging: 2, trialRun: 3, layoutAdjustment: 2 },
    rampUp: [
      { hour: 1, efficiency: 58, target: 55, piecesProduced: 48 },
      { hour: 2, efficiency: 68, target: 65, piecesProduced: 56 },
      { hour: 3, efficiency: 73, target: 70, piecesProduced: 60 },
      { hour: 4, efficiency: 76, target: 74, piecesProduced: 62 },
      { hour: 5, efficiency: 78, target: 75, piecesProduced: 64 },
      { hour: 6, efficiency: 79, target: 75, piecesProduced: 65 },
      { hour: 7, efficiency: 80, target: 75, piecesProduced: 65 },
      { hour: 8, efficiency: 80, target: 75, piecesProduced: 65 },
    ],
    defectRatePct: 4.6,
    notes: 'Ramp-up exceeded target in Hour 1. Best performance to date. Setting cards fully effective.',
    phase: 'full-smed',
  },
  {
    id: 'log-apr-29',
    date: '2026-04-29',
    lineId: 'line-10',
    fromStyleCode: 'ARL-SH-CARGO-24',
    toStyleCode: 'ARL-SH-CHINO-24',
    smedException: true,
    t1CompletionPct: 96,
    totalDurationMin: 27,
    internalTimeMin: 20,
    externalTimeSavedMin: 83,
    breakdown: { wipClearance: 3, machineSetup: 5, threadPrep: 2, attachmentHandling: 1, operatorDemo: 1, fabricStaging: 2, trialRun: 3, layoutAdjustment: 2 },
    rampUp: [
      { hour: 1, efficiency: 61, target: 55, piecesProduced: 50 },
      { hour: 2, efficiency: 70, target: 65, piecesProduced: 57 },
      { hour: 3, efficiency: 75, target: 70, piecesProduced: 61 },
      { hour: 4, efficiency: 78, target: 74, piecesProduced: 64 },
      { hour: 5, efficiency: 80, target: 75, piecesProduced: 65 },
      { hour: 6, efficiency: 81, target: 75, piecesProduced: 66 },
      { hour: 7, efficiency: 81, target: 75, piecesProduced: 66 },
      { hour: 8, efficiency: 82, target: 75, piecesProduced: 67 },
    ],
    defectRatePct: 3.9,
    notes: 'Near-perfect T-1 execution. Zero WIP at end of T-1 shift. Defect rate below 4% for first time.',
    phase: 'full-smed',
  },
  {
    id: 'log-apr-30',
    date: '2026-04-30',
    lineId: 'line-9',
    fromStyleCode: 'ARL-SH-CHINO-24',
    toStyleCode: 'ARL-SH-DENIM-25',
    smedException: true,
    t1CompletionPct: 100,
    totalDurationMin: 24,
    internalTimeMin: 18,
    externalTimeSavedMin: 86,
    breakdown: { wipClearance: 2, machineSetup: 5, threadPrep: 2, attachmentHandling: 1, operatorDemo: 1, fabricStaging: 1, trialRun: 3, layoutAdjustment: 2 },
    rampUp: [
      { hour: 1, efficiency: 65, target: 55, piecesProduced: 53 },
      { hour: 2, efficiency: 73, target: 65, piecesProduced: 60 },
      { hour: 3, efficiency: 77, target: 70, piecesProduced: 63 },
      { hour: 4, efficiency: 80, target: 74, piecesProduced: 65 },
      { hour: 5, efficiency: 82, target: 75, piecesProduced: 67 },
      { hour: 6, efficiency: 83, target: 75, piecesProduced: 68 },
      { hour: 7, efficiency: 84, target: 75, piecesProduced: 69 },
      { hour: 8, efficiency: 84, target: 75, piecesProduced: 69 },
    ],
    defectRatePct: 3.2,
    notes: 'All 9 T-1 tasks 100% complete. Full SMED SOP executed perfectly. Best changeover time on record.',
    phase: 'full-smed',
  },
];
